config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('shop/', include('shop.urls',namespace='shop')),
    path('users/',include('users.urls',namespace='users')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
=======
    path('shop/', include('shop.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e

shop/urls.py
from django.urls import path
from .views import index,product_detail,order_detail,create_product,delete_product,comment_create

<<<<<<< HEAD
app_name = 'shop'
=======

>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e

urlpatterns = [
    # product crud
    path('',index,name='index'),
    path('category/<int:category_id>/',index, name='products_by_category'),
    path('detail/<int:product_id>/',product_detail,name='product_detail'),
    path('product/create/',create_product,name='create_product'),
    path('product/delete/<int:pk>/',delete_product,name='delete_product'),
    # order logic
  
    path('order/detail/<int:pk>/',order_detail,name='order_detail'),
    path('comment/create/<int:pk>',comment_create,name='comment_create')
<<<<<<< HEAD
]

=======
]
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e

users/urls.py
from django.urls import path
from users.views import login_page,logout_page
app_name = 'users'

urlpatterns = [
    path('login-page/',login_page,name='login_page'),
    path('logout-page/',logout_page,name='logout_page')
]

shop/models.py
from django.db import models
from decimal import Decimal
# Create your models here.


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
<<<<<<< HEAD
    my_order = models.PositiveIntegerField(
        default=0,
        null=True,
        blank=True
    )
    
    class Meta:
        abstract = True
        
=======
    
    class Meta:
        abstract = True
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e

class Category(BaseModel):
    title = models.CharField(max_length=100,unique=True)
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'categories'
        verbose_name = 'category'
<<<<<<< HEAD
        ordering = ['my_order']
        db_table = 'category'
=======
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e


class Product(BaseModel):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True,blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='products/')
    discount = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category,related_name='products',on_delete=models.SET_NULL,null=True,blank=True)
    amount = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return self.name

    
    @property
    def discounted_price(self):
        if self.discount > 0:
            return self.price * Decimal(f'{1 - (self.discount / 100)}')
        return self.price
    
    @property
    def get_absolute_url(self):
        if self.image:
            return self.image.url
        return ''
    
    class Meta:
        verbose_name_plural = 'products'
        verbose_name = 'product'
<<<<<<< HEAD
        ordering = ['my_order']
        db_table = 'product'
=======
        ordering = ['-price']
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e



class Order(BaseModel):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    quantity = models.PositiveIntegerField(default=1)
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                related_name='orders',
                                null=True,blank=True
                                )
    
    def __str__(self):
        return f'{self.name} - {self.quantity}'


<<<<<<< HEAD
    class Meta:
        db_table = 'order'
=======

>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e


class Comment(BaseModel):
    class RatingChoices(models.IntegerChoices):
        ZERO = 0
        ONE = 1
        TWO = 2
        THREE = 3
        FOUR = 4
        FIVE = 5
        
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()
    product = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='comments')
    rating = models.IntegerField(choices = RatingChoices.choices,default = RatingChoices.THREE.value)
    
    def __str__(self):
<<<<<<< HEAD
        return f'{self.name} - {self.rating}'
    
    class Meta:
        db_table = 'comment'
=======
        return f'{self.name} - {self.rating}'
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e

shop/forms.py
from django import forms
from shop.models import Order,Product,Comment

# class OrderForm(forms.Form): #forms.ModelForm
#     name = forms.CharField(max_length=150)
#     phone = forms.CharField(max_length=20)
#     quantity = forms.IntegerField(blank = True)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        # fields = ['name','phone','quantity']  
        exclude = ('created_at','updated_at','product')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('created_at','updated_at','product')
        

shop/views.py
from django.shortcuts import render,redirect
from .models import Product,Category
from django.contrib import messages
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from .forms import OrderForm,ProductForm,CommentForm
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.db.models.functions import Round
<<<<<<< HEAD
from .utils import product_rating_filter
=======
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e




# Create your views here.


def index(request,category_id=None):
    search_query = request.GET.get('q','')
    filter_type = request.GET.get('filter','')
    categories = Category.objects.all()
    
    
    
    
    if category_id:
        products = Product.objects.filter(category = category_id)
    else:
        products = Product.objects.all() #.order_by('-price')
        
    
        
    if search_query:
        products = products.filter(name__icontains = search_query)
        
    products = products.annotate(avg_rating = Round(Avg('comments__rating'),precision = 2) )

<<<<<<< HEAD
    products = product_rating_filter(filter_type,products)
   
=======
        
    if filter_type == 'expensive':
        products = products.order_by('-price')
    
    elif filter_type == 'cheap':
        products = products.order_by('price')
        
    
    elif filter_type == 'rating':
        products = products.order_by('-avg_rating')
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
    
    # DRY => Dont Repeat Yourself
    
        
    
    
    context = {
        'products': products,
        'categories': categories
    }
    return render(request, 'shop/home.html',context)


def product_detail(request,product_id):
    try:
        product = Product.objects.get(id = product_id)
<<<<<<< HEAD
        related_products = Product.objects.filter(category = product.category).exclude(id=product.id)
        context = {
            'product':product,
            'related_products':related_products,
            }
=======
        context = {'product':product}
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
        return render(request,'shop/detail.html',context)
    
    except Product.DoesNotExist:
        return HttpResponse('Product Not Found')
    
    
def order_detail(request,pk):
    # product = Product.objects.get(id = pk)
    product = get_object_or_404(Product,pk=pk)
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.product = product
            if product.amount < order.quantity or order.quantity == 0:
                # send message
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Don\'t have enough product quantity'
                )
              
               
            else:
                product.amount -= order.quantity
                product.save()
                order.save()
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Item successfully ordered'
                )
<<<<<<< HEAD
                return redirect('shop:product_detail',pk)
=======
                return redirect('product_detail',pk)
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
    context = {
        'form':form,
        'product':product
    }
            
    return render(request,'shop/detail.html',context = context)
            
            
@login_required
def create_product(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
<<<<<<< HEAD
            return redirect('shop:index')
=======
            return redirect('index')
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
    
    context = {
        'form':form
    }
    return render(request,'shop/product/create.html',context)


@login_required
def edit_product(request):
    pass


@login_required
def delete_product(request,pk):
    product = get_object_or_404(Product,pk=pk)
    if request.method == 'POST':
        product.delete()
<<<<<<< HEAD
        return redirect('shop:index')
=======
        return redirect('index')
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
    return render(request,'shop/product/delete.html',{'product':product})




def comment_create(request,pk):
    product =  get_object_or_404(Product,pk=pk)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        comment = form.save(commit=False)
        comment.product = product
        comment.save()
<<<<<<< HEAD
        return redirect('shop:product_detail',pk)
=======
        return redirect('product_detail',pk)
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
    
    return render(request,'shop/detail.html',{'form':form})

shop/templates/shop/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
<<<<<<< HEAD
                                <li><a class="dropdown-item" href="{% url 'shop:index' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for category in categories%}
                                    <li><a class="dropdown-item" href="{% url 'shop:products_by_category' category.id %}">{{category.title}}</a></li>
=======
                                <li><a class="dropdown-item" href="{% url 'index' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for category in categories%}
                                    <li><a class="dropdown-item" href="{% url 'products_by_category' category.id %}">{{category.title}}</a></li>
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                                {%endfor%}
                            </ul>
                        </li>
                    </ul>
                    <form method="get" class="d-flex">
                        <input type="text" class="form-contro" name="q">
<<<<<<< HEAD
                        <button style="margin-right: 50px;" class="btn btn-outline-dark" type="submit">
=======
                        <button class="btn btn-outline-dark" type="submit">
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                            <i class="bi-search-fill me-1"></i>
                            Search
                           
                        </button>
                    </form>
<<<<<<< HEAD

                  
                    
                    {% if user.is_authenticated %}
                    <form method="post" action="{% url 'users:logout_page' %}">
                        {%csrf_token%}
                        <div> 
                                <button  type="submit" class="btn btn-primary">
                                    Logout
                                </button>
                            {{user.email}}
                        </div>
                    </form>
                    {%else%}
                        <div>
                            <a href="{% url 'users:login_page' %}">
                                <button  type="button" class="btn btn-primary">
                                    Login
                                </button>
                            </a>
                        </div>

                    {%endif%}
=======
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shop in style</h1>
                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                </div>
            </div>
        </header>
        <!-- Section-->

        <div class="container mt-5">
            <div class="text-left">
                <h3>Filter by</h3>
            </div>
            <div class="row">
                <div class="col-1">
                    <a class="btn btn-outline-dark mt-auto" href="?filter=expensive"> Expensive </a>
                </div>

                <div class="col-1">
                    <a class="btn btn-outline-dark mt-auto" href="?filter=cheap"> Cheap </a>
                </div>

                <div class="col-1">
                    <a class="btn btn-outline-dark mt-auto" href="?filter=rating"> Rating </a>
                </div>
                {%if user.is_authenticated%}
                    <div class="col-1">
<<<<<<< HEAD
                        <a href="{% url 'shop:create_product' %}">
=======
                        <a href="{% url 'create_product' %}">
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                            <button type="button" class="btn btn-success" style="font-size: 16px; padding: 10px 20px; border-radius: 8px;">
                                ➕ ADD PRODUCT
                            </button>
                        </a>
                    </div>
                {%endif%}

            </div>
        </div>
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products %}
                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Sale badge-->
                                {% if product.discount %}
                                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                                {%endif%}

                                <!-- Product image-->
<<<<<<< HEAD
                                <a href="{% url 'shop:product_detail' product.id %}">
=======
                                <a href="{% url 'product_detail' product.id %}">
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                                    <img class="card-img-top" src="{{product.get_absolute_url}}" alt="..." />
                                </a>
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{product.name}}</h5>
                                        <!-- Product reviews-->
                                        <div class="">
                                            Rating : {{product.avg_rating}}
                                        </div>
                                        <!-- Product price-->
                                        {%if product.discount%}
                                            <span class="text-muted text-decoration-line-through">${{product.price}}</span>
                                            ${{product.discounted_price}} 
                                        {%else%}
                                            ${{product.discounted_price}} 
                                        {%endif%}
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
<<<<<<< HEAD
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'shop:product_detail' product.id %}">View product</a></div>
=======
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product_detail' product.id %}">View product</a></div>
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e
                                
                                    
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'shop/js/scripts.js' %}"></script>
    </body>
<<<<<<< HEAD
</html>
=======
</html>
>>>>>>> 7065014f6ba19135e4a15716eb87ce3569946d8e